# Generated by Django 3.2.6 on 2021-08-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('author_user_id', models.CharField(max_length=150)),
                ('issue_id', models.CharField(max_length=150)),
                ('created_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('projet_id', models.IntegerField()),
                ('permission', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('tag', models.CharField(max_length=150)),
                ('priority', models.CharField(max_length=150)),
                ('projetct_id', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('author_user_id', models.CharField(max_length=150)),
                ('assignee_user_id', models.CharField(max_length=150)),
                ('created_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
